"""Initial schema

Revision ID: 4951f61c7ebd
Revises: 
Create Date: 2026-03-24 00:46:47.282263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4951f61c7ebd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('acknowledged', sa.Boolean(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alerts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=True),
    sa.Column('alert_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('data_json', sa.Text(), nullable=True),
    sa.Column('acknowledged', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_ticker'), 'alerts', ['ticker'], unique=False)
    op.create_table('analysis_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('composite_score', sa.Float(), nullable=True),
    sa.Column('technical_strength', sa.Float(), nullable=True),
    sa.Column('options_sentiment', sa.Float(), nullable=True),
    sa.Column('short_opportunity', sa.Float(), nullable=True),
    sa.Column('squeeze_risk', sa.Float(), nullable=True),
    sa.Column('funding_strength', sa.Float(), nullable=True),
    sa.Column('macro_pressure', sa.Float(), nullable=True),
    sa.Column('valuation_attractiveness', sa.Float(), nullable=True),
    sa.Column('action', sa.String(length=30), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('target_price', sa.Float(), nullable=True),
    sa.Column('stop_price', sa.Float(), nullable=True),
    sa.Column('forecast_point', sa.Float(), nullable=True),
    sa.Column('forecast_lower', sa.Float(), nullable=True),
    sa.Column('forecast_upper', sa.Float(), nullable=True),
    sa.Column('var_95', sa.Float(), nullable=True),
    sa.Column('max_drawdown', sa.Float(), nullable=True),
    sa.Column('full_analysis', sa.JSON(), nullable=True),
    sa.Column('data_sources', sa.JSON(), nullable=True),
    sa.Column('warnings_count', sa.Integer(), nullable=True),
    sa.Column('mock_data_used', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_analysis_ticker_ts', 'analysis_records', ['ticker', 'timestamp'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('event_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_type', sa.String(length=60), nullable=False),
    sa.Column('entity', sa.String(length=100), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('user_or_system', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('backtest_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('strategy', sa.String(length=100), nullable=False),
    sa.Column('params', sa.JSON(), nullable=True),
    sa.Column('total_return', sa.Float(), nullable=True),
    sa.Column('sharpe_ratio', sa.Float(), nullable=True),
    sa.Column('max_drawdown', sa.Float(), nullable=True),
    sa.Column('win_rate', sa.Float(), nullable=True),
    sa.Column('total_trades', sa.Integer(), nullable=True),
    sa.Column('results', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('backtest_runs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('run_name', sa.String(length=200), nullable=False),
    sa.Column('strategy_name', sa.String(length=100), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('timeframe', sa.String(length=16), nullable=False),
    sa.Column('total_return', sa.Float(), nullable=True),
    sa.Column('annualized_return', sa.Float(), nullable=True),
    sa.Column('sharpe_ratio', sa.Float(), nullable=True),
    sa.Column('sortino_ratio', sa.Float(), nullable=True),
    sa.Column('calmar_ratio', sa.Float(), nullable=True),
    sa.Column('max_drawdown', sa.Float(), nullable=True),
    sa.Column('win_rate', sa.Float(), nullable=True),
    sa.Column('avg_win', sa.Float(), nullable=True),
    sa.Column('avg_loss', sa.Float(), nullable=True),
    sa.Column('payoff_ratio', sa.Float(), nullable=True),
    sa.Column('expectancy', sa.Float(), nullable=True),
    sa.Column('total_trades', sa.Integer(), nullable=True),
    sa.Column('profit_factor', sa.Float(), nullable=True),
    sa.Column('alpha_vs_spy', sa.Float(), nullable=True),
    sa.Column('beta_vs_spy', sa.Float(), nullable=True),
    sa.Column('performance_by_regime_json', sa.Text(), nullable=True),
    sa.Column('parameters_json', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backtest_runs_ticker'), 'backtest_runs', ['ticker'], unique=False)
    op.create_table('backtest_trades',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.BigInteger(), nullable=False),
    sa.Column('trade_number', sa.Integer(), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('vehicle', sa.String(length=30), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('exit_date', sa.Date(), nullable=True),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('position_size', sa.Float(), nullable=True),
    sa.Column('pnl', sa.Float(), nullable=True),
    sa.Column('pnl_pct', sa.Float(), nullable=True),
    sa.Column('holding_days', sa.Integer(), nullable=True),
    sa.Column('exit_reason', sa.String(length=50), nullable=True),
    sa.Column('regime_at_entry', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backtest_trades_run_id'), 'backtest_trades', ['run_id'], unique=False)
    op.create_table('data_quality_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('check_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_source', sa.String(length=60), nullable=False),
    sa.Column('table_name', sa.String(length=60), nullable=False),
    sa.Column('issue_type', sa.String(length=40), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('earnings_releases',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('report_time', sa.String(length=10), nullable=True),
    sa.Column('eps_estimate', sa.Float(), nullable=True),
    sa.Column('eps_actual', sa.Float(), nullable=True),
    sa.Column('eps_surprise', sa.Float(), nullable=True),
    sa.Column('revenue_estimate', sa.Float(), nullable=True),
    sa.Column('revenue_actual', sa.Float(), nullable=True),
    sa.Column('revenue_surprise', sa.Float(), nullable=True),
    sa.Column('pre_earnings_iv', sa.Float(), nullable=True),
    sa.Column('post_earnings_iv', sa.Float(), nullable=True),
    sa.Column('implied_move', sa.Float(), nullable=True),
    sa.Column('realized_move', sa.Float(), nullable=True),
    sa.Column('post_earnings_drift_5d', sa.Float(), nullable=True),
    sa.Column('post_earnings_drift_20d', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('source_label', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('freshness_seconds', sa.Integer(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=False),
    sa.Column('is_stale', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_earnings_releases_ticker'), 'earnings_releases', ['ticker'], unique=False)
    op.create_table('financial_statements',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('period', sa.Date(), nullable=False),
    sa.Column('period_type', sa.String(length=4), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('revenue', sa.Float(), nullable=True),
    sa.Column('fee_revenue', sa.Float(), nullable=True),
    sa.Column('cost_of_revenue', sa.Float(), nullable=True),
    sa.Column('gross_profit', sa.Float(), nullable=True),
    sa.Column('gross_margin', sa.Float(), nullable=True),
    sa.Column('operating_expense', sa.Float(), nullable=True),
    sa.Column('operating_income', sa.Float(), nullable=True),
    sa.Column('operating_margin', sa.Float(), nullable=True),
    sa.Column('ebitda', sa.Float(), nullable=True),
    sa.Column('adjusted_ebitda', sa.Float(), nullable=True),
    sa.Column('net_income', sa.Float(), nullable=True),
    sa.Column('net_margin', sa.Float(), nullable=True),
    sa.Column('eps_basic', sa.Float(), nullable=True),
    sa.Column('eps_diluted', sa.Float(), nullable=True),
    sa.Column('cash_and_equivalents', sa.Float(), nullable=True),
    sa.Column('total_debt', sa.Float(), nullable=True),
    sa.Column('total_assets', sa.Float(), nullable=True),
    sa.Column('total_liabilities', sa.Float(), nullable=True),
    sa.Column('shareholders_equity', sa.Float(), nullable=True),
    sa.Column('shares_outstanding', sa.BigInteger(), nullable=True),
    sa.Column('shares_diluted', sa.BigInteger(), nullable=True),
    sa.Column('operating_cash_flow', sa.Float(), nullable=True),
    sa.Column('capex', sa.Float(), nullable=True),
    sa.Column('free_cash_flow', sa.Float(), nullable=True),
    sa.Column('contribution_profit', sa.Float(), nullable=True),
    sa.Column('contribution_margin', sa.Float(), nullable=True),
    sa.Column('revenue_guidance_low', sa.Float(), nullable=True),
    sa.Column('revenue_guidance_high', sa.Float(), nullable=True),
    sa.Column('ebitda_guidance_low', sa.Float(), nullable=True),
    sa.Column('ebitda_guidance_high', sa.Float(), nullable=True),
    sa.Column('management_commentary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('source_label', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('freshness_seconds', sa.Integer(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=False),
    sa.Column('is_stale', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'period', 'period_type', name='uq_financial')
    )
    op.create_index(op.f('ix_financial_statements_ticker'), 'financial_statements', ['ticker'], unique=False)
    op.create_table('forecast_validations',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('forecast_id', sa.BigInteger(), nullable=False),
    sa.Column('actual_value', sa.Float(), nullable=False),
    sa.Column('error', sa.Float(), nullable=False),
    sa.Column('abs_error', sa.Float(), nullable=False),
    sa.Column('pct_error', sa.Float(), nullable=True),
    sa.Column('within_interval', sa.Boolean(), nullable=True),
    sa.Column('brier_score', sa.Float(), nullable=True),
    sa.Column('direction_correct', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forecast_validations_forecast_id'), 'forecast_validations', ['forecast_id'], unique=False)
    op.create_table('forecasts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('forecast_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('horizon_days', sa.Integer(), nullable=False),
    sa.Column('target_variable', sa.String(length=50), nullable=False),
    sa.Column('model_name', sa.String(length=60), nullable=False),
    sa.Column('point_estimate', sa.Float(), nullable=True),
    sa.Column('lower_bound', sa.Float(), nullable=True),
    sa.Column('upper_bound', sa.Float(), nullable=True),
    sa.Column('confidence_level', sa.Float(), nullable=False),
    sa.Column('probability_up', sa.Float(), nullable=True),
    sa.Column('probability_down', sa.Float(), nullable=True),
    sa.Column('probability_flat', sa.Float(), nullable=True),
    sa.Column('regime_context', sa.String(length=50), nullable=True),
    sa.Column('assumptions_json', sa.Text(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('source_label', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('freshness_seconds', sa.Integer(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=False),
    sa.Column('is_stale', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forecasts_ticker'), 'forecasts', ['ticker'], unique=False)
    op.create_table('funding_facilities',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('facility_name', sa.String(length=200), nullable=False),
    sa.Column('partner_name', sa.String(length=200), nullable=True),
    sa.Column('facility_type', sa.String(length=50), nullable=False),
    sa.Column('committed', sa.Boolean(), nullable=False),
    sa.Column('facility_size', sa.Float(), nullable=True),
    sa.Column('drawn_amount', sa.Float(), nullable=True),
    sa.Column('available_amount', sa.Float(), nullable=True),
    sa.Column('maturity_date', sa.Date(), nullable=True),
    sa.Column('revolving_period_end', sa.Date(), nullable=True),
    sa.Column('interest_rate_type', sa.String(length=50), nullable=True),
    sa.Column('spread_bps', sa.Float(), nullable=True),
    sa.Column('advance_rate', sa.Float(), nullable=True),
    sa.Column('has_covenant', sa.Boolean(), nullable=False),
    sa.Column('covenant_details', sa.Text(), nullable=True),
    sa.Column('has_waiver', sa.Boolean(), nullable=False),
    sa.Column('waiver_details', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('renewal_probability', sa.Float(), nullable=True),
    sa.Column('filing_source', sa.Text(), nullable=True),
    sa.Column('last_updated_from_filing', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('source_label', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('freshness_seconds', sa.Integer(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=False),
    sa.Column('is_stale', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_funding_facilities_ticker'), 'funding_facilities', ['ticker'], unique=False)
    op.create_table('funding_partners',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('partner_name', sa.String(length=200), nullable=False),
    sa.Column('partner_type', sa.String(length=50), nullable=True),
    sa.Column('relationship_start', sa.Date(), nullable=True),
    sa.Column('is_forward_flow', sa.Boolean(), nullable=False),
    sa.Column('forward_flow_commitment', sa.Float(), nullable=True),
    sa.Column('products_covered', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('concentration_pct', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('source_label', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('freshness_seconds', sa.Integer(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=False),
    sa.Column('is_stale', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_funding_partners_ticker'), 'funding_partners', ['ticker'], unique=False)
    op.create_table('insider_transactions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('filing_date', sa.Date(), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=True),
    sa.Column('insider_name', sa.String(length=200), nullable=True),
    sa.Column('insider_title', sa.String(length=200), nullable=True),
    sa.Column('transaction_type', sa.String(length=50), nullable=True),
    sa.Column('shares', sa.BigInteger(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('shares_owned_after', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('source_label', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('freshness_seconds', sa.Integer(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=False),
    sa.Column('is_stale', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insider_transactions_ticker'), 'insider_transactions', ['ticker'], unique=False)
    op.create_table('institutional_ownership',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('institution_name', sa.String(length=300), nullable=False),
    sa.Column('shares_held', sa.BigInteger(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('pct_of_portfolio', sa.Float(), nullable=True),
    sa.Column('change_shares', sa.BigInteger(), nullable=True),
    sa.Column('change_pct', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('source_label', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('freshness_seconds', sa.Integer(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=False),
    sa.Column('is_stale', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_institutional_ownership_ticker'), 'institutional_ownership', ['ticker'], unique=False)
    op.create_table('macro_indicators',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('indicator', sa.String(length=50), nullable=False),
    sa.Column('observation_date', sa.Date(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('prior_value', sa.Float(), nullable=True),
    sa.Column('change', sa.Float(), nullable=True),
    sa.Column('z_score', sa.Float(), nullable=True),
    sa.Column('percentile', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=30), nullable=True),
    sa.Column('frequency', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('source_label', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('freshness_seconds', sa.Integer(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=False),
    sa.Column('is_stale', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('indicator', 'observation_date', name='uq_macro')
    )
    op.create_index(op.f('ix_macro_indicators_indicator'), 'macro_indicators', ['indicator'], unique=False)
    op.create_table('news_intelligence_snapshots',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('snapshot_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('news_intelligence_score', sa.Float(), nullable=True),
    sa.Column('overall_sentiment', sa.Float(), nullable=True),
    sa.Column('sentiment_label', sa.String(length=20), nullable=True),
    sa.Column('sentiment_trend', sa.String(length=20), nullable=True),
    sa.Column('total_articles', sa.Integer(), nullable=False),
    sa.Column('news_count', sa.Integer(), nullable=False),
    sa.Column('social_count', sa.Integer(), nullable=False),
    sa.Column('ir_count', sa.Integer(), nullable=False),
    sa.Column('ceo_count', sa.Integer(), nullable=False),
    sa.Column('ceo_sentiment', sa.Float(), nullable=True),
    sa.Column('ceo_tone', sa.String(length=20), nullable=True),
    sa.Column('ceo_activity_level', sa.String(length=20), nullable=True),
    sa.Column('retail_sentiment', sa.Float(), nullable=True),
    sa.Column('social_trending', sa.Boolean(), nullable=False),
    sa.Column('bull_bear_ratio', sa.Float(), nullable=True),
    sa.Column('dominant_narrative', sa.Text(), nullable=True),
    sa.Column('narrative_shift', sa.Boolean(), nullable=False),
    sa.Column('risk_flags', sa.Text(), nullable=True),
    sa.Column('opportunity_signals', sa.Text(), nullable=True),
    sa.Column('analysis_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_intelligence_snapshots_ticker'), 'news_intelligence_snapshots', ['ticker'], unique=False)
    op.create_table('news_items',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('headline', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('source_name', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('sentiment_label', sa.String(length=20), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('policy_risk_flag', sa.Boolean(), nullable=False),
    sa.Column('world_risk_flag', sa.Boolean(), nullable=False),
    sa.Column('funding_flag', sa.Boolean(), nullable=False),
    sa.Column('earnings_flag', sa.Boolean(), nullable=False),
    sa.Column('upst_transmission_score', sa.Float(), nullable=True),
    sa.Column('transmission_reasoning', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('source_label', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('freshness_seconds', sa.Integer(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=False),
    sa.Column('is_stale', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_items_ticker'), 'news_items', ['ticker'], unique=False)
    op.create_table('options_chains',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('snapshot_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('underlying_price', sa.Float(), nullable=False),
    sa.Column('total_call_volume', sa.Integer(), nullable=False),
    sa.Column('total_put_volume', sa.Integer(), nullable=False),
    sa.Column('total_call_oi', sa.Integer(), nullable=False),
    sa.Column('total_put_oi', sa.Integer(), nullable=False),
    sa.Column('put_call_volume_ratio', sa.Float(), nullable=True),
    sa.Column('put_call_oi_ratio', sa.Float(), nullable=True),
    sa.Column('iv_rank', sa.Float(), nullable=True),
    sa.Column('iv_percentile', sa.Float(), nullable=True),
    sa.Column('expected_move', sa.Float(), nullable=True),
    sa.Column('max_pain', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('source_label', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('freshness_seconds', sa.Integer(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=False),
    sa.Column('is_stale', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_options_chains_ticker'), 'options_chains', ['ticker'], unique=False)
    op.create_table('options_contracts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('chain_id', sa.BigInteger(), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('option_type', sa.String(length=4), nullable=False),
    sa.Column('strike', sa.Float(), nullable=False),
    sa.Column('expiration', sa.Date(), nullable=False),
    sa.Column('bid', sa.Float(), nullable=True),
    sa.Column('ask', sa.Float(), nullable=True),
    sa.Column('mark', sa.Float(), nullable=True),
    sa.Column('last', sa.Float(), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.Column('open_interest', sa.Integer(), nullable=False),
    sa.Column('implied_volatility', sa.Float(), nullable=True),
    sa.Column('delta', sa.Float(), nullable=True),
    sa.Column('gamma', sa.Float(), nullable=True),
    sa.Column('theta', sa.Float(), nullable=True),
    sa.Column('vega', sa.Float(), nullable=True),
    sa.Column('rho', sa.Float(), nullable=True),
    sa.Column('in_the_money', sa.Boolean(), nullable=True),
    sa.Column('days_to_expiry', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('source_label', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('freshness_seconds', sa.Integer(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=False),
    sa.Column('is_stale', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_opt_ticker_exp_strike', 'options_contracts', ['ticker', 'expiration', 'strike'], unique=False)
    op.create_index(op.f('ix_options_contracts_chain_id'), 'options_contracts', ['chain_id'], unique=False)
    op.create_table('origination_data',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('period', sa.Date(), nullable=False),
    sa.Column('period_type', sa.String(length=10), nullable=False),
    sa.Column('product_type', sa.String(length=50), nullable=False),
    sa.Column('origination_volume', sa.Float(), nullable=True),
    sa.Column('loan_count', sa.Integer(), nullable=True),
    sa.Column('avg_loan_size', sa.Float(), nullable=True),
    sa.Column('conversion_rate', sa.Float(), nullable=True),
    sa.Column('approval_rate', sa.Float(), nullable=True),
    sa.Column('avg_apr', sa.Float(), nullable=True),
    sa.Column('avg_model_score', sa.Float(), nullable=True),
    sa.Column('yoy_growth', sa.Float(), nullable=True),
    sa.Column('qoq_growth', sa.Float(), nullable=True),
    sa.Column('mom_growth', sa.Float(), nullable=True),
    sa.Column('fee_revenue_from_origination', sa.Float(), nullable=True),
    sa.Column('take_rate', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('source_label', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('freshness_seconds', sa.Integer(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=False),
    sa.Column('is_stale', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_origination_data_ticker'), 'origination_data', ['ticker'], unique=False)
    op.create_table('price_bars',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('timeframe', sa.String(length=16), nullable=False),
    sa.Column('bar_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.Column('vwap', sa.Float(), nullable=True),
    sa.Column('trade_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('source_label', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('freshness_seconds', sa.Integer(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=False),
    sa.Column('is_stale', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'timeframe', 'bar_time', name='uq_pricebar')
    )
    op.create_index(op.f('ix_price_bars_ticker'), 'price_bars', ['ticker'], unique=False)
    op.create_index('ix_pricebar_ticker_time', 'price_bars', ['ticker', 'bar_time'], unique=False)
    op.create_table('score_snapshots',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('snapshot_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('score_name', sa.String(length=60), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('components_json', sa.Text(), nullable=True),
    sa.Column('weights_json', sa.Text(), nullable=True),
    sa.Column('inputs_freshness_json', sa.Text(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('source_label', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('freshness_seconds', sa.Integer(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=False),
    sa.Column('is_stale', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_score_snapshots_score_name'), 'score_snapshots', ['score_name'], unique=False)
    op.create_index(op.f('ix_score_snapshots_ticker'), 'score_snapshots', ['ticker'], unique=False)
    op.create_table('sec_filings',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('filing_type', sa.String(length=20), nullable=False),
    sa.Column('filed_date', sa.Date(), nullable=False),
    sa.Column('period_of_report', sa.Date(), nullable=True),
    sa.Column('accession_number', sa.String(length=30), nullable=False),
    sa.Column('filing_url', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('has_funding_info', sa.Boolean(), nullable=False),
    sa.Column('has_covenant_info', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('source_label', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('freshness_seconds', sa.Integer(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=False),
    sa.Column('is_stale', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('accession_number')
    )
    op.create_index(op.f('ix_sec_filings_ticker'), 'sec_filings', ['ticker'], unique=False)
    op.create_table('securitizations',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('deal_name', sa.String(length=200), nullable=False),
    sa.Column('issuance_date', sa.Date(), nullable=True),
    sa.Column('deal_size', sa.Float(), nullable=True),
    sa.Column('collateral_type', sa.String(length=100), nullable=True),
    sa.Column('weighted_avg_coupon', sa.Float(), nullable=True),
    sa.Column('weighted_avg_life', sa.Float(), nullable=True),
    sa.Column('subordination_pct', sa.Float(), nullable=True),
    sa.Column('initial_cnl_estimate', sa.Float(), nullable=True),
    sa.Column('current_cnl', sa.Float(), nullable=True),
    sa.Column('delinquency_30d', sa.Float(), nullable=True),
    sa.Column('delinquency_60d', sa.Float(), nullable=True),
    sa.Column('delinquency_90d', sa.Float(), nullable=True),
    sa.Column('cumulative_default_rate', sa.Float(), nullable=True),
    sa.Column('deal_status', sa.String(length=20), nullable=False),
    sa.Column('rating_agency', sa.String(length=50), nullable=True),
    sa.Column('senior_tranche_rating', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('source_label', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('freshness_seconds', sa.Integer(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=False),
    sa.Column('is_stale', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_securitizations_ticker'), 'securitizations', ['ticker'], unique=False)
    op.create_table('short_interest',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('short_interest', sa.BigInteger(), nullable=True),
    sa.Column('shares_float', sa.BigInteger(), nullable=True),
    sa.Column('short_pct_float', sa.Float(), nullable=True),
    sa.Column('days_to_cover', sa.Float(), nullable=True),
    sa.Column('avg_volume_30d', sa.BigInteger(), nullable=True),
    sa.Column('short_change_pct', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('source_label', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('freshness_seconds', sa.Integer(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=False),
    sa.Column('is_stale', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'report_date', name='uq_short_interest')
    )
    op.create_index(op.f('ix_short_interest_ticker'), 'short_interest', ['ticker'], unique=False)
    op.create_table('signals',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('signal_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('engine', sa.String(length=60), nullable=False),
    sa.Column('signal_name', sa.String(length=100), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('strength', sa.Float(), nullable=False),
    sa.Column('timeframe', sa.String(length=16), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('data_inputs_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('source_label', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('freshness_seconds', sa.Integer(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=False),
    sa.Column('is_stale', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signals_ticker'), 'signals', ['ticker'], unique=False)
    op.create_table('stock_loan',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('cost_to_borrow', sa.Float(), nullable=True),
    sa.Column('utilization', sa.Float(), nullable=True),
    sa.Column('shares_available', sa.BigInteger(), nullable=True),
    sa.Column('lendable_shares', sa.BigInteger(), nullable=True),
    sa.Column('borrow_fee_trend', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('source_label', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('freshness_seconds', sa.Integer(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=False),
    sa.Column('is_stale', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'snapshot_date', name='uq_stock_loan')
    )
    op.create_index(op.f('ix_stock_loan_ticker'), 'stock_loan', ['ticker'], unique=False)
    op.create_table('trade_decisions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('decision_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('timeframe', sa.String(length=16), nullable=False),
    sa.Column('action', sa.String(length=30), nullable=False),
    sa.Column('vehicle', sa.String(length=30), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=True),
    sa.Column('target_price', sa.Float(), nullable=True),
    sa.Column('stop_price', sa.Float(), nullable=True),
    sa.Column('invalidation_price', sa.Float(), nullable=True),
    sa.Column('reward_risk_ratio', sa.Float(), nullable=True),
    sa.Column('expected_value', sa.Float(), nullable=True),
    sa.Column('suggested_position_pct', sa.Float(), nullable=True),
    sa.Column('max_loss_pct', sa.Float(), nullable=True),
    sa.Column('trade_quality_score', sa.Float(), nullable=True),
    sa.Column('signal_agreement_pct', sa.Float(), nullable=True),
    sa.Column('fragility_score', sa.Float(), nullable=True),
    sa.Column('dominant_factors_json', sa.Text(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('what_would_change', sa.Text(), nullable=True),
    sa.Column('risk_factors', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('source_label', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('freshness_seconds', sa.Integer(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=False),
    sa.Column('is_stale', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trade_decisions_ticker'), 'trade_decisions', ['ticker'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trade_decisions_ticker'), table_name='trade_decisions')
    op.drop_table('trade_decisions')
    op.drop_index(op.f('ix_stock_loan_ticker'), table_name='stock_loan')
    op.drop_table('stock_loan')
    op.drop_index(op.f('ix_signals_ticker'), table_name='signals')
    op.drop_table('signals')
    op.drop_index(op.f('ix_short_interest_ticker'), table_name='short_interest')
    op.drop_table('short_interest')
    op.drop_index(op.f('ix_securitizations_ticker'), table_name='securitizations')
    op.drop_table('securitizations')
    op.drop_index(op.f('ix_sec_filings_ticker'), table_name='sec_filings')
    op.drop_table('sec_filings')
    op.drop_index(op.f('ix_score_snapshots_ticker'), table_name='score_snapshots')
    op.drop_index(op.f('ix_score_snapshots_score_name'), table_name='score_snapshots')
    op.drop_table('score_snapshots')
    op.drop_index('ix_pricebar_ticker_time', table_name='price_bars')
    op.drop_index(op.f('ix_price_bars_ticker'), table_name='price_bars')
    op.drop_table('price_bars')
    op.drop_index(op.f('ix_origination_data_ticker'), table_name='origination_data')
    op.drop_table('origination_data')
    op.drop_index(op.f('ix_options_contracts_chain_id'), table_name='options_contracts')
    op.drop_index('ix_opt_ticker_exp_strike', table_name='options_contracts')
    op.drop_table('options_contracts')
    op.drop_index(op.f('ix_options_chains_ticker'), table_name='options_chains')
    op.drop_table('options_chains')
    op.drop_index(op.f('ix_news_items_ticker'), table_name='news_items')
    op.drop_table('news_items')
    op.drop_index(op.f('ix_news_intelligence_snapshots_ticker'), table_name='news_intelligence_snapshots')
    op.drop_table('news_intelligence_snapshots')
    op.drop_index(op.f('ix_macro_indicators_indicator'), table_name='macro_indicators')
    op.drop_table('macro_indicators')
    op.drop_index(op.f('ix_institutional_ownership_ticker'), table_name='institutional_ownership')
    op.drop_table('institutional_ownership')
    op.drop_index(op.f('ix_insider_transactions_ticker'), table_name='insider_transactions')
    op.drop_table('insider_transactions')
    op.drop_index(op.f('ix_funding_partners_ticker'), table_name='funding_partners')
    op.drop_table('funding_partners')
    op.drop_index(op.f('ix_funding_facilities_ticker'), table_name='funding_facilities')
    op.drop_table('funding_facilities')
    op.drop_index(op.f('ix_forecasts_ticker'), table_name='forecasts')
    op.drop_table('forecasts')
    op.drop_index(op.f('ix_forecast_validations_forecast_id'), table_name='forecast_validations')
    op.drop_table('forecast_validations')
    op.drop_index(op.f('ix_financial_statements_ticker'), table_name='financial_statements')
    op.drop_table('financial_statements')
    op.drop_index(op.f('ix_earnings_releases_ticker'), table_name='earnings_releases')
    op.drop_table('earnings_releases')
    op.drop_table('data_quality_logs')
    op.drop_index(op.f('ix_backtest_trades_run_id'), table_name='backtest_trades')
    op.drop_table('backtest_trades')
    op.drop_index(op.f('ix_backtest_runs_ticker'), table_name='backtest_runs')
    op.drop_table('backtest_runs')
    op.drop_table('backtest_records')
    op.drop_table('audit_logs')
    op.drop_index('idx_analysis_ticker_ts', table_name='analysis_records')
    op.drop_table('analysis_records')
    op.drop_index(op.f('ix_alerts_ticker'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_table('alert_records')
    # ### end Alembic commands ###
